# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5714682f66225db7d8c76e3d519d05f4d602d9a68c01ff47791fb9070411fa52cdd868a2c5a5108b7139e5f7f4f4192fededc904dc9e5e47a36a2d648c7811b

test:
  secret_key_base: 1fbfc421403e9128d84ac658836cd5a2fd3a3260c6aca60f12acb55dd5ddb0acc92ebded20594e632832c23106d797214a3c1f6d435ebee05ec8cf9dce3f48b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
